# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e9e0bef32b42361f19befbf24f1bd1af473d9d9e73e16bc7d4578bfbfe4168fa47546a7683d8f05bb7f1c640945226b1207250dfa224e100e58ee6e84f8a03

test:
  secret_key_base: 66567c7db3746bf9ddef3c19610a48f8d4779d9f6d983de809a1036876dfe1c8e422c251bf4cec3451a8842543928124560a467949cd20e02c009ad7255f257b

# Do not keep production secrets in the repository,
# instead read values from the environment.